version: '3.8'

services:
  ical-sync:
    build: .
    image: ical-to-gcal:latest
    volumes:
      - ./credentials:/app/credentials
      - ./data:/app/data
    environment:
      - CREDENTIALS_PATH=/app/credentials/credentials.json
      - TOKEN_PATH=/app/credentials/token.json
      - ICS_URL=${ICS_URL}
      - CALENDAR_ID=${CALENDAR_ID}
      - SYNC_FLAGS=${SYNC_FLAGS:---dry-run}
    # The entrypoint script will use these environment variables
    # command: # Controlled by environment variables
    
  # Service for one-time credential setup
  setup:
    build: .
    image: ical-to-gcal:latest
    volumes:
      - ./credentials:/app/credentials
      - ./data:/app/data
    environment:
      - CREDENTIALS_PATH=/app/credentials/credentials.json
      - TOKEN_PATH=/app/credentials/token.json
    command: list_calendars.py
    profiles:
      - setup

  # Service for listing calendars
  list-calendars:
    build: .
    image: ical-to-gcal:latest
    volumes:
      - ./credentials:/app/credentials
      - ./data:/app/data
    environment:
      - CREDENTIALS_PATH=/app/credentials/credentials.json
      - TOKEN_PATH=/app/credentials/token.json
    command: python list_calendars.py
    profiles:
      - tools

  # Scheduled sync service (runs every 6 hours)
  scheduler:
    image: mcuadros/ofelia:latest
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      # Run the ical-sync service every 1 hour
      ofelia.job-service-run.ical-sync.schedule: "0 */1 * * *"
      ofelia.job-service-run.ical-sync.service: "ical-sync"
    profiles:
      - scheduler
